### PR TITLE
Merging staging into main for spring 15 (February 4th)

### PR DESCRIPTION
**Pull request by dym-chen**

### CODE REVIEW

**Review by dericky1 — COMMENTED** [review]
All the routes work for me. There is one issue I ran into. /fre2 is weirdly spaced for me. Attached a picture,
PR#80-fre2

**Comment by SealsJ** [comment]
Opening the newest deployment, the account error message is displaying on just normal /sign-in page. This is before actually trying to sign in. The error message isn't displaying on sign-up so that page is working correctly!
Screenshot 2024-02-04 223215

**Review by dericky1 — CHANGES_REQUESTED** [review]
LGTM, one last thing not sure if that button above the share button should have that spacing/color
pr#80-fre2-color

**Review by dericky1 — APPROVED** [review]
LGTM

**Pull request merged**
