### PR TITLE
feature(fullstack): Implementing Sendbird Prebuilt Components

### PR DESCRIPTION
**Pull request by SealsJ**
Added Basic Sendbird Functionality to our platform for users to be able chat with each other.
- Utilizes Clerk ID to create Sendbird User Account: Currently showcases Clerk ID but will be removed when updating UI.
- Still Need to Connect Sendbird to our Groups API
- Still Need to Update UI to reflect our design for user messaging
- APP_ID for Sendbird is currently visible but according to Sendbird community this is okay, only API tokens should never be revealed

### CODE REVIEW

**Review by lai-kevin — APPROVED** [review]
LGTM!

Are we going to use prebuilt components with modified styling or will we make our own components?

**Review by rodmen07 — APPROVED** [review]
Looks good!

**Comment by dericky1** [comment]
Rod mentioned getstream.io as another way to implement chat? Have you guys discussed and decided on using SendBird? @SealsJ @rodmen07

**Comment by rodmen07** [comment]
> Rod mentioned getstream.io as another way to implement chat? Have you guys discussed and decided on using SendBird? @SealsJ @rodmen07

Haven't brought it up with Jeremy yet, but I can lay out some positives for why I think Stream might fit our build slightly better at this point:
-Emphasis on customizability of ui components and functionality. This is a bit more involved with Sendbird, and we are somewhat limited to simply adding components on top of existing ui unless we reverse engineer Sendbird's core components.
-Good availability of learning resources on web (Youtube, blogs, etc.)
-More liberal free plan (From site: "If your project/company has less than 5 team members and less than $10k in monthly revenue, Stream is free/gratis/complimentary.")
-Similar implementation to Sendbird with slight differences, so as to not lose a lot of time relearning new library.

**Comment by rodmen07** [comment]
Not sure if this is an issue with my user account or if another change may have affected the deployment, but now when I manually navigate to the messages page in the vercel preview I get an error:
"Application error: a client-side exception has occurred (see the browser console for more information)."
Going into the console logs, it seems like user.id is undefined for the Chat component.
Note: I am able to login with an existing account/user in Clerk
image

**Comment by dericky1** [comment]
> > Rod mentioned getstream.io as another way to implement chat? Have you guys discussed and decided on using SendBird? @SealsJ @rodmen07
> 
> Haven't brought it up with Jeremy yet, but I can lay out some positives for why I think Stream might fit our build slightly better at this point: -Emphasis on customizability of ui components and functionality. This is a bit more involved with Sendbird, and we are somewhat limited to simply adding components on top of existing ui unless we reverse engineer Sendbird's core components. -Good availability of learning resources on web (Youtube, blogs, etc.) -More liberal free plan (From site: "If your project/company has less than 5 team members and less than $10k in monthly revenue, Stream is free/gratis/complimentary.") -Similar implementation to Sendbird with slight differences, so as to not lose a lot of time relearning new library.

Lets go over sendbird vs getstream in the Thursday dev meeting.

**Comment by lai-kevin** [comment]
> Not sure if this is an issue with my user account or if another change may have affected the deployment, but now when I manually navigate to the messages page in the vercel preview I get an error: "Application error: a client-side exception has occurred (see the browser console for more information)." Going into the console logs, it seems like user.id is undefined for the Chat component. Maybe there needs to be a conditional check for user before rendering the component, or we should persist the user to state and then provide to the component. Note: I am able to login with an existing account/user in Clerk image

Probably caused by improper handling of errors

**Pull request closed without merging**
